### ISSUE TITLE
Firefox tab & URL bar font (Ubuntu)

### ISSUE THREAD

**Issue by edent** [eosrei/emojione-color-font#1]
Firstly, thank you for this colour font - it works wonderfully in Firefox on Ubuntu.

The only issue is that the text on tabs, in the URL bar, menus, etc now uses a Serif font which looks a bit ugly.

Is there any way to keep the Emoji font, but have FF use a different fallback font for its application text?

Hope I've explained that well enough :-)

**Comment by 13rac1** [comment]
You're welcome! :smile: It's been a lot of work and I've learned a lot.

Oh [fontconfig](https://wiki.archlinux.org/index.php/Font_configuration) is so much fun! :tada: 

[I'm running MATE](https://raw.githubusercontent.com/eosrei/emojione-color-font/master/images/linux-firefox.png) with a theme and it is using the correct font for the Firefox UI. That's my excuse for not noticing it! :) I just confirmed, it's fine in my Fedora VM also. I haven't tried it in the newest Ubuntu though.

The `fonts.conf` in the readme adds `Emoji One Color` to the sans-serif, serif and monospace lists separately, which as I understand, shouldn't change the overall font used. The font contains no letter glyphs, so the next font in the list should be used. Can you give me the list of fallback fonts for sans-serif?

Here's how to do it and the first few entries in my list are:

``` sh
user@server ~ $ fc-match -s sans-serif
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "SVGinOT"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
n019003l.pfb: "Nimbus Sans L" "Regular"
Waree.ttf: "Waree" "Book"
DroidSansFallbackFull.ttf: "Droid Sans Fallback" "Regular"
KhmerOS.ttf: "Khmer OS" "Regular"
MuktiNarrow.ttf: "Mukti Narrow" "Regular"
NanumGothic.ttf: "NanumGothic" "Regular"
lohit_bn.ttf: "Lohit Bengali" "Regular"
lohit_gu.ttf: "Lohit Gujarati" "Regular"
lohit_pa.ttf: "Lohit Punjabi" "Regular"
lohit_ta.ttf: "Lohit Tamil" "Regular"
Meera_04.ttf: "Meera" "Regular"
lklug.ttf: "LKLUG" "Regular"
```

I had to have `Emoji One Color` before `DejaVu` since `DejaVu` provides a number of B&W emoji glyphs.

**Comment by edent** [comment]
Aha! I am also running MATE. Love that Cinnamon taste.

For future adventurers, I went to System Settings -> Fonts -> Default font.  Then selected "Ubuntu 10".

All looking good, and no need to fiddle with command lines or config files.

**Comment by 13rac1** [comment]
Ok! Great! Let me know if you see anything else that needs work :+1:

**Comment by valpackett** [comment]
For people who don't use desktop environments: this means setting your GTK font to your preferred font, not "sans-serif"

**Comment by 13rac1** [comment]
@myfreeweb :+1: Thanks!

**Comment by salty-horse** [comment]
I _think_ you're describing the same bug as mine, which is a regression in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1254245

**Comment by 13rac1** [comment]
I just noticed Firefox was still using DejaVu Sans as the source for some emoji even though my new fonts.conf has it far down the list. Setting `gfx.font_rendering.fontconfig.fontlist.enabled` to `false` and restarting fixed the problem. Setting it back to `true` kept the new internal font list, sort of a cache clear.
