### ISSUE TITLE
Add Summary License File

### ISSUE THREAD

**Issue by IgnoredAmbience** [eosrei/emojione-color-font#13]
I'm currently packaging the font for the [Arch Linux AUR](https://aur.archlinux.org/), it'd be helpful if the git source provided a copy of the License section of README.md in its own file, so that can just be installed into the relevant location.

**Comment by IgnoredAmbience** [comment]
This section also lacks a precise statement of what license the compiled .ttf file lies under, I assume a combination of the CC-BY-4 ones?

**Comment by IgnoredAmbience** [comment]
(The aforementioned Arch Linux AUR package is here: https://aur.archlinux.org/packages/emojione-color-font/)

**Comment by 13rac1** [comment]
Thanks for making a Arch package!

> it'd be helpful if the git source provided a copy of the License section of README.md in its own file

No problem, the README.md has been growing lately, and moving much of this a separate file is a good way to reduce.

> precise statement of what license the compiled .ttf file lies under

Good point. It's actually in the font file itself. You can see the details in the scfbuild settings: https://github.com/eosrei/emojione-color-font/blob/f68b4da412a60aaf7edf3eaffbc75f856d46509b/scfbuild.yml#L34

This is good place to mention a related issue, perhaps you have some thoughts on the matter? As I understand it, this font cannot go in the Debian repos due to the CC-BY licensing: http://lwn.net/Articles/128461/ and the strict Emoji One attribution requirements: http://emojione.com/licensing/ I'm actually willing to rebuild the twemoji graphics and license all of my work Open Font License, but I'm limited by the Emoji One attribution requirements. I cannot license less than CC-BY-4.0 at this point.

**Comment by 13rac1** [comment]
Q: Is DejaVu the default font on arch?

**Comment by 13rac1** [comment]
I've tried to be explicit about the limitations of this font due to the Apple vs Microsoft vs Google vs Adobe/Mozilla/W3C color font specification mess. You may want to make it clear that color is only supported in Firefox/Thunderbird right now.

**Comment by 13rac1** [comment]
> Q: Is DejaVu the default font on arch?

To answer my own Q, I just checked my Arch VM and it's yes.

**Comment by IgnoredAmbience** [comment]
Debian [is ok with CC-BY-SA 4.0](https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_Share-Alike_.28CC-BY-SA.29_v4.0).
The attribution requirements that Emoji One require are within the spirit of the license, up to the interpretation of 'reasonable':

> 3a1Ai) If You Share the Licensed Material (including in modified form), You must: retain the following if it is supplied by the Licensor with the Licensed Material: identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);

Arch doesn't have a default (TrueType) font per se, I think it prompts you to pick a package that satisfies the ttf-font dependency on the first requirement.

Thanks for the suggestion, I will clarify that in the package description field.

**Comment by IgnoredAmbience** [comment]
That said, the package description field is already too long. I've just bundled the readme instead. I hope Arch users will be clever enough to read the documentation, if they're interested enough in the package.

**Comment by 13rac1** [comment]
Ah, ok, I found info about CC2.0. Of course, that would be a reason to fix it!

My concern is the attribution requirements applying to the user of the font. Perhaps I'm going too far down the line, but if this were a default font, for example, in Ubuntu it's unreasonable to expect someone to understand they need to print attribution on a commercial work using it. Not a problem for anyone at this point though, so I'll deal with that in the future.

> Arch doesn't have a default (TrueType) font per se, I think it prompts you to pick a package that satisfies the ttf-font dependency on the first requirement.

That'll work either way. I'm using the DejaVu Sans space widths to fix #2 so I wanted to be sure it wouldn't be a problem for Arch. Only DejaVu Sans has the characters needing to be overriden, so I'm going to adjust the serif and mono settings in the `font.conf` to give them priority. Sigh... I had no idea what I was getting into when I started with the question: "Why is there a broken character displayed in my gmail inbox?" Ha!

> Thanks for the suggestion, I will clarify that in the package description field.

The b&w will work everywhere, that's why I insisted on making them. I just don't want Chrome users expecting color.

**Comment by IgnoredAmbience** [comment]
> Sigh... I had no idea what I was getting into when I started with the question: "Why is there a broken character displayed in my gmail inbox?" Ha!

I started down this path yesterday/today wondering why there were broken symbols output in my console by a unit test runner... (Bit of a way until SVG-in-OT is supported by a terminal though!)

**Comment by 13rac1** [comment]
@edgemaster FYI I created a 1.0-beta2 release. 

> That said, the package description field is already too long.

Was thinking about this further, I'd give up part of what it includes to emphasize the Firefox "dependency".

```
A color emoji unicode SVGinOT font supporting diversity and country flags. Firefox required for color.
```

Or something like that.

**Comment by IgnoredAmbience** [comment]
I added a [post-install message](https://aur.archlinux.org/cgit/aur.git/tree/emojione-color-font.install?h=emojione-color-font) in the end to reinforce this, along with the licensing issue.

**Comment by 13rac1** [comment]
Perfect!
