### ISSUE TITLE
Replacing existing characters on Ubuntu; Conky fonts turns to boxes, Firefox becomes serif

### ISSUE THREAD

**Issue by nshiff** [eosrei/emojione-color-font#18]
Before
<img src=http://i.imgur.com/oAjcVPN.png>

After
<img src=http://i.imgur.com/IClYe6P.png>

Firefox fonts changes take effect immediately after install. Conky happens after logging out and logging back in. I am running Ubuntu 14.04 with Cinnamon 2.8.6.

**Comment by 13rac1** [comment]
Thanks for making the issue!

This looks a whole lot like #1 for Firefox. It's closed, because there's nothing I can do (other than add it to the readme file of known issues.. which I need to do.)

As for Conky, what font do you have it set to? The font fallback system is what allows programs to specify a font, but still get characters (glyphs) from other fonts for languages such as Arabic and Chinese. `Emoji One Color` doesn't have any letter/number characters, so if the program doesn't _know_ how to use the Linux font fallback system this sort of thing can/will happen. It should fall back to the next font in line, generally, `DejaVu Sans` when your application requests `Sans-Serif`. Some programs, like VLC #5, will **only** use that the selected font, so you need to specify a font.

This would absolutely be solved by the extreme solution in #17.

**Comment by 13rac1** [comment]
In the meantime, you can leave the font installed, but not install the `fonts.conf`. `DejaVu Sans` will take top priority, so you'll see it where ever it has a code point. `Emoji One Color` will cover everything else.

**Comment by 13rac1** [comment]
Should be fixed by https://github.com/eosrei/emojione-color-font/commit/24b65391c1f02f8ff57b7b4f9c12f94550bac0ca

Additional options later.

**Comment by 13rac1** [comment]
@nshiff Did beta3 work for you?
