### ISSUE TITLE
Mathematica font breaking

### ISSUE THREAD

**Issue by kjschanney** [eosrei/emojione-color-font#33]
Hi,
i am on arch linux,
these fonts break the Mathematica fonts. To restore Mathematica just remove them.
hope this information helps.

**Comment by 13rac1** [comment]
I'd much rather fix the problem instead of ignoring it. Can you please describe the issue and post a screenshot?

Are you running the latest beta3?

**Comment by kjschanney** [comment]
Hi,
I am on Arch linux using Mathematica version 10. When i installed emojione-color-fonts from [aur](https://aur.archlinux.org/packages/emojione-color-font/) all the mathematical symbols in mathematica breaks like \alpha \beta and \gamma e.t.c. 
Here is a screenshot [link](https://aur.archlinux.org/packages/emojione-color-font/)
This kind of problem occured once before but for some other reasons. Have a look at the arch thread [Link](https://bbs.archlinux.org/viewtopic.php?id=184112)
I have to break my Mathematica again to generate the same bug. 
Let me know if you need any kind of log or something.

**Comment by 13rac1** [comment]
Thank for you the reply. The screenshot link you posted is incorrect. Could you update it?

I've read the forum thread. Fonts seem to be a standard problem with Mathematica 10: http://mathematica.stackexchange.com/questions/55711/wrong-font-selection-for-some-characters-in-mathematica-10-for-linux

**Comment by kjschanney** [comment]
Hi, correct screenshot is [Link](http://oi57.tinypic.com/2n80inl.jpg)
![2n80inl](https://cloud.githubusercontent.com/assets/195061/15050245/59cabe58-12a7-11e6-8364-59521365b6e2.jpg)
Yes it may be the problem with Mathematica as i don't see any other application get effected like emacs or lyx or any other app which shows scientific fonts.

_edit by eosrei to embed image_

**Comment by 13rac1** [comment]
The missing glyph boxes are exactly what I expect to see when a program isn't correctly using font libraries. I've seen this type of problem before in #5, #18, #23, but those were all due to EmojiOne Color being the default font. The [recommended configuration](https://github.com/eosrei/emojione-color-font/blob/8442bc6523bb5ac7113c247dab6b4c4768c2df36/linux/fontconfig/56-emojione-color.conf) no longer makes it the default font, which corrects all of those issues.

You could try the [font config tests](https://github.com/eosrei/emojione-color-font/tree/8442bc6523bb5ac7113c247dab6b4c4768c2df36/linux/tests) to confirm your configuration is working as designed/recommended. Hmm... Perhaps this is something like the Firefox font list issue #31 and Mathematica caches the original font list, so newly installed fonts are incorrectly selected.

**Comment by 13rac1** [comment]
Q: Have you installed Bitstream Vera? It is marked optional in the AUR, but it is _required_ for the provided configuration to work.

Related: #35

**Comment by 13rac1** [comment]
No response in two weeks. Closing issue. I'll re-open if needed.
