### ISSUE TITLE
Font in Firefox is forced to Bitstream Vera Sans

### ISSUE THREAD

**Issue by hackerb9** [eosrei/emojione-color-font#51]
Hello. As you probably know, when using Firefox with the current /etc/fonts/conf.d/56-emojione-color.conf, ugly things happen to the default font. In particular, even if the user has picked a specific font from the Firefox preferences, Bitstream Vera Sans will always be used.

I do not know the correct fix for this, but I have a temporary workaround. Font-config can ignore any programs that are named Firefox (or Iceweasel, for older versions of Debian GNU/Linux). Since Firefox seems to work fine without the 56-emojione-color.conf file, this is a harmless kludge.

Here's a patch:

```
 --- 56-emojione-color.conf.orig 2016-06-10 11:44:50.000000000 -0700
 +++ 56-emojione-color.conf 2016-08-06 09:20:57.000000000 -0700
 @@ -71,11 +71,18 @@
 </edit>
 </match>

 + <!-- XXX Firefox default font bug is somewhere below this line. -->
 <match target="pattern">
 <!-- If the requested font is sans-serif -->
 <test qual="any" name="family">
 <string>sans-serif</string>
 </test>
 + <test qual="any" name="prgname" compare="not_contains">
 + <string>firefox</string>
 + </test>
 + <test qual="any" name="prgname" compare="not_contains">
 + <string>iceweasel</string>
 + </test>
 <!-- Make Bitstream Vera Sans the first result -->
 <edit name="family" mode="prepend_first">
 <string>Bitstream Vera Sans</string>
 @@ -85,6 +92,7 @@
 <string>EmojiOne Color</string>
 </edit>
 </match>
 + <!-- XXX Firefox default font bug is above this line. -->

 <match target="font">
 <!-- If the requested font is Bitstream Vera Sans Mono -->
```

I apologize for not providing a correct fix, but I have not yet learned the weird fonts.conf XML language. (So far, I think the FC decision to use XML to represent a programming language is rather barfy. I'd rather they just gave me a regular language and had a "compiler" to convert it to XML.)
### Versions
- Firefox-ESR 45.3.0
- Debian GNU/Linux 8, Jessie
- Latest emojione-color.conf from github.

I'm attaching the debug output from running Firefox with the environment variable FC_DEBUG=1 both with and without the patch so you can see how FC is picking the fonts.
[fcdebug.prepatch.txt](https://github.com/eosrei/emojione-color-font/files/405107/fcdebug.prepatch.txt)
[fcdebug.postpatch.txt](https://github.com/eosrei/emojione-color-font/files/405108/fcdebug.postpatch.txt)
### Here is what Firefox looks like when using emojione without my patch:

![incorrect-font-in-firefox-prepatch](https://cloud.githubusercontent.com/assets/10174223/17458149/ac1fa7da-5bbe-11e6-8fc8-6778bf642d47.png)
### Applying my patch, Firefox now uses the correct font:

![correct-font-in-firefox-postpatch](https://cloud.githubusercontent.com/assets/10174223/17458154/bf30fafe-5bbe-11e6-8776-0a518b8ce9e7.png)

**Comment by 13rac1** [comment]
> Since Firefox seems to work fine without the 56-emojione-color.conf file, this is a harmless kludge.

The [demo page](http://eosrei.github.io/emojione-color-font/full-demo.html) works without it because it specifically selects the font, but does: http://getemoji.com/ ?

**Comment by hackerb9** [comment]
Okay, this is kind of bizarre. It seems 56-emojione-color.conf appears to be doing the reverse of what it is supposed to. I just tested it in Firefox and found out that when I use the current version, I get the problem with Deja Vu replacing some of the Emoji with black and white versions. (I tried it on both the demo page and getemoji with the same results).

#### The default version:

![emojione-dejavu-problems-prepatch](https://cloud.githubusercontent.com/assets/10174223/17458358/e1e2e284-5bc2-11e6-9c3e-a9266677868a.png)
![emojione-dejavu-problems-prepatch2](https://cloud.githubusercontent.com/assets/10174223/17458360/e6d38f14-5bc2-11e6-9608-502a0fd0b09f.png)

#### However, after my patch...

 But, when I use my patched version of the file, all the emoji show up correctly:

![emojione-works-postpatch](https://cloud.githubusercontent.com/assets/10174223/17458365/0651248c-5bc3-11e6-864e-3dcf254e9c9c.png)
![emojione-works-postpatch2](https://cloud.githubusercontent.com/assets/10174223/17458366/0a3fb284-5bc3-11e6-9749-e1b528aa4619.png)

Curiouser and curiouser.

**Comment by 13rac1** [comment]
Are you running `fc-cache -f` after these changes? I have had many issues with delays in the caching system like this.

**Comment by hackerb9** [comment]
I alternated changes so that as soon as the cache updated, I'd see the browser change. Usually it seems to be about 15 to 30 seconds, so I didn't have any problem. 

I just tried again with fc-cache -f, with the same results. (By the way, flushing the cache manually didn't make the update happen any faster. I still had to wait about the same amount of time before the browser window updated. I think fontconfig must be using inotify or something similar so that it gets alerted as soon as the config file is edited.)

**Comment by hackerb9** [comment]
(Oops, I notice that in my first message I mistakenly left in a line about Firefox working without the entire file. I meant without the particular stanza that I am skipping over. Sorry for the confusion.)

**Comment by 13rac1** [comment]
I recommend restarting Firefox between changes. It updates, but things go all wrong sometimes. More when changing glyphs though.

**Comment by hackerb9** [comment]
I double checked by restarting it after each change and it still behaved the same: the current conf file has the DejaVu smiley faces but when I remove (or make conditional) that stanza, as suggested in my first patch, it works fine. And, of course, my patch also fixes the problem with the Bitstream Vera overriding the default font in Firefox.

Are you not seeing the same behavior on your machine? What version of Firefox are you using? Do you have the DejaVu fonts installed?

**Comment by pelegm** [comment]
I am not 100% sure this is the same issue, but I have a similar problem on my Ubuntu 14.04 with Firefox. Each time after installing this package (via the ppa) the default font in Firefox (including but not limited to the font appearing on the tabs) starts looking weird (especially the spacings). In some websites (stack exchange, wolfram alpha) this causes the page to look horrible. I'll add a couple of images.

![tabtitle](https://cloud.githubusercontent.com/assets/3422626/17579401/c52b2fbe-5f9d-11e6-9942-4f5546650fc4.png)
![stacktitle](https://cloud.githubusercontent.com/assets/3422626/17579408/d768a79c-5f9d-11e6-847f-74e007d8691c.png)
![wolframtitle](https://cloud.githubusercontent.com/assets/3422626/17579415/e69b7e1a-5f9d-11e6-86d6-9164d50df57a.png)

**Comment by pelegm** [comment]
Compare this with:

![tabtitle2](https://cloud.githubusercontent.com/assets/3422626/17579444/424e18b2-5f9e-11e6-8f68-cc13fe1d9227.png)
![stacktitle2](https://cloud.githubusercontent.com/assets/3422626/17579445/4574d012-5f9e-11e6-818d-58df63b92c6a.png)
![wolframtitle2](https://cloud.githubusercontent.com/assets/3422626/17579447/4795b85c-5f9e-11e6-94b7-5eb4eb59f390.png)

**Comment by 13rac1** [comment]
@pelegm That's a known issue: https://github.com/eosrei/emojione-color-font#known-issues It's bug in Firefox which you can correct, but will cause it to crash in versions <48. The internal font list is wrong. Nothing I can do AFAIK. @hackerb9 It is related to this issue.

> Are you not seeing the same behavior on your machine?

No. Please test it with a stock 16.04 ISO in Virtualbox. You don't need to install to the virtual disk, the Live CD works fine. I know exactly how it works on Ubuntu 14.04/16.04 and Fedora 22.

> What version of Firefox are you using?

48, the current repo version.

> Do you have the DejaVu fonts installed? 

Yes. Stock Linux Mint 18/Ubuntu 16.04 fontconfig, plus my PPA.

![FF48+PPA](https://cloud.githubusercontent.com/assets/195061/17584846/a694e87c-5f6d-11e6-851f-1901b078671f.png)

Related, it's actually not Bitstream being disabled. If you open the fonts and look at the glyphs they are exactly the same as DejaVu. Haha, so much fun! That's why this is distinctly a Firefox problem. If you set `gfx.font_rendering.fontconfig.fontlist.enabled` to `false` it displays everything correctly.

I've been extremely busy and haven't been able to test your config until now. Your font config additions, as you know, disable the font pattern matching for sans-serif in Firefox. I implemented it and watched the correct text fonts display on getemoji.com. I wondered why for a moment, then realized the secondary fallbacks were being used.

```
  <alias binding="strong">
    <family>Segoe UI Emoji</family>
    <prefer><family>EmojiOne Color</family></prefer>
    <default><family>sans-serif</family></default>
  </alias>
```

That page specifically calls out `font-family: Segoe UI Emoji;` in the CSS.

So, I tried another page that requires the existing fallback system: https://en.wikipedia.org/wiki/Emoji Ah, there we go, broken emoji. Your config:
![your config](https://cloud.githubusercontent.com/assets/195061/17584677/cef526e8-5f6c-11e6-88e8-121bcda8fb89.png)
The default config:
![existing config](https://cloud.githubusercontent.com/assets/195061/17584727/15234d2a-5f6d-11e6-9060-b88344afcfee.png)

_Note: You will see problems due to #22 on that page in the "Sample emoji variation sequences", but that's out of scope of this issue._

I'd be happy if we can figure out a permanent solution to this issue, but your current idea isn't it. Please try more ideas! Thanks!

**Comment by 13rac1** [comment]
The current workaround is described in: https://github.com/eosrei/emojione-color-font#known-issues and #31.

I'm closing this for now. Please add another comment or open a PR if you have ideas for a solution. Thank you!
