### ISSUE TITLE
Upstream have their own SVG in OpenType font

### ISSUE THREAD

**Issue by auscompgeek** [eosrei/emojione-color-font#73]
It appears EmojiOne also distribute their own SVG in OpenType font, using the 2.2.7 glyphs: https://github.com/Ranks/emojione/tree/master/extras/fonts

Maybe we should note this in the README or something. I dunno.

We should also have a look at what's different in their version. I haven't had a chance to take a look myself.

**Comment by 13rac1** [comment]
I am aware it exists. My font existed long before upstream's. This [was listed in the upstream repo](https://github.com/Ranks/emojione/commit/875213a8ba15801f40df476163f1257023798cd6#diff-c5f39d3a62c36e89b0864e0bfa949ef2) as the recommended SVG font until removed without warning. Upstream had no obligation to contact me, but still... 🙍‍♂️. A negative experience. I would have been happy to work with them.

I haven't finished the ~next~ last ⚰️  release of this font yet. Only minor changes other than a fix for Windows. It will be the last due to the 3.0 licensing (see #71) I recommend switching to [twemoji-color-font](https://github.com/eosrei/twemoji-color-font). I will officially deprecate this and update the README if/when Twitter releases a Unicode 10 update. Also, keep an eye on: https://github.com/EmojiTwo/emojitwo

**Comment by 13rac1** [comment]
The primary difference is the black and white designs. See #62
