### ISSUE TITLE
Could you please explain how to add new symbols?

### ISSUE THREAD

**Issue by survtur** [eosrei/emojione-color-font#91]
I'd like to add WHITE SUN 0x1F323 symbol. Is it enough to add only svg file with proper name `/assets/emojione-svg/1f323.svg`?

**Comment by 13rac1** [comment]
Yes, that how it works!

Note: I am not accepting graphic changes to this repo. This project has ended due to upstream licensing changes.

**Comment by Crissov** [comment]
… and [Emojitwo](http://GitHub.com/EmojiTwo/emojitwo/) already has a graphic for U+1F323. Over there, we are very happy about any contributed graphics. A font build process is already set up and will run with each release. Since the fork from Emojione 2.2 in April, we did not yet have a proper release. This will happen when either support for Emoji 4+5 / Unicode 10 is complete or when we cover all characters that are not officially emoji, but are supported by Samsung, LG or Microsoft.

**Comment by survtur** [comment]
@Crissov Wow, there is no mentions of EmojiTwo in readme. Glad you wrote it here.

**Comment by survtur** [comment]
@Crissov I like the idea of Emojitwo. But I'm not so skilled to compile font files myself. It would be nice to have nightly builds additionally to releases.

**Comment by 13rac1** [comment]
I'll be directing users to EmojiTwo once it's complete. In the meantime, Unicode 10 emoji are available here: https://github.com/eosrei/twemoji-color-font although U+1F323 is missing. @Crissov has already made an issue upstream: https://github.com/twitter/twemoji/issues/169
