### ISSUE TITLE
Alien and moneybag emoji are broken on Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [eosrei/emojione-color-font#93]
Followed the instructions and downloaded and installed `EmojiOneColor-SVGinOT-Linux-1.3` using the `./install.sh` script. Looking at the emoji one test page (http://eosrei.github.io/emojione-color-font/full-demo.html) I found that the moneybag and alien emoji look broken:

[Alien Screenshot](https://i.imgur.com/j6mcUFE.png)
[Moneybag screenshot](https://i.imgur.com/KwDotGK.png)

OS: Ubuntu 16.04
Browser: Firefox 57.0

**Comment by 13rac1** [comment]
Can you test the actual SVGs?

* Moneybag: https://github.com/eosrei/emojione-color-font/blob/master/assets/emojione-svg/1f4b0.svg
* Alien: https://github.com/eosrei/emojione-color-font/blob/master/assets/emojione-svg/1f47d.svg

I'm surprised to just hear about this now. FWIW This project is sunset due to the upstream licensing change. I'll fix this is someone PRs it, but in general I recommend everyone switch to: https://github.com/eosrei/twemoji-color-font

**Comment by 1Hyena** [comment]
@eosrei 
I on Linux Mint here and the same bug is also apparent here.
Installed the fonts according to the instructions given here:
http://www.omgubuntu.co.uk/2016/06/emoji-one-font-linux-unicode-9-0

I tried out links to actual svg and they were displaying correctly though

**Comment by 1Hyena** [comment]
A discovery! I experienced a buggy moneybag just like OP but after executing the below line the bug disappeared because the moneybag sprite got replaced by a different one that does not appear as buggy.

`sudo apt-get install fonts-twemoji-svginot` <-- this fixed it for me

**Comment by 13rac1** [comment]
The upstream SVGs are partially invalid. :disappointed: 

Closing, because I will not be fixing this issue in the final release.
